version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: meu_correspondente_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meu_correspondente
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: meu_correspondente_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/meu_correspondente?schema=public
      - PORT=3000
    depends_on:
      - db

volumes:
  pgdata:
